<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX5cn8jc\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX5cn8jc/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX5cn8jc.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX5cn8jc\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerX5cn8jc\srcDevDebugProjectContainer([
    'container.build_hash' => 'X5cn8jc',
    'container.build_id' => 'aa7c8ef2',
    'container.build_time' => 1570009548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX5cn8jc');
