<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWemavma\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWemavma/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWemavma.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWemavma\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWemavma\srcDevDebugProjectContainer([
    'container.build_hash' => 'Wemavma',
    'container.build_id' => 'ae2389c1',
    'container.build_time' => 1570089472,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWemavma');
