<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJenpxhl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJenpxhl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJenpxhl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJenpxhl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJenpxhl\srcDevDebugProjectContainer([
    'container.build_hash' => 'Jenpxhl',
    'container.build_id' => '3fd52c6e',
    'container.build_time' => 1570011691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJenpxhl');
